const STORE = 'intendencia-ordenes-v1';
const BUILDINGS = ['Diagonal Roque Sáenz Peña 1211','Av. Callao 635','Montevideo 546'];
const STATUSES = ['Pendiente','En proceso','Faltan insumos','Resuelto','Sin asignar'];
const PRIORITIES = ['Urgente','Alta','Media','Baja'];
const CATEGORIES = ['Mantenimiento general','Electricidad','Sanitarios','Pintura','Carpintería','Aire acondicionado','Ascensores','Limpieza','Movimiento interno','Seguridad','Albañilería','Tapicería','Administrativo'];
const SPECIALTIES = ['Carpintería','Aires Acondicionados','Albañilería','Ayudante','Electricidad','Plomería','Tapicería','Pintura','Administrativo'];
const CATEGORY_SPECIALTY = {'Carpintería':'Carpintería','Aire acondicionado':'Aires Acondicionados','Mantenimiento general':'Ayudante','Electricidad':'Electricidad','Sanitarios':'Plomería','Pintura':'Pintura','Movimiento interno':'Ayudante','Limpieza':'Ayudante','Ascensores':'Electricidad','Seguridad':'Electricidad','Albañilería':'Albañilería','Tapicería':'Tapicería','Administrativo':'Administrativo'};
const SERVICE_TYPES = ['Caldera','Tanques','Fumigación','Limpieza','Aires acondicionados','Ascensores','Otro'];
const CLAIM_REASONS = {
  'Caldera':['Falta de calefacción','Pérdida de agua','Ruidos o funcionamiento irregular','Mantenimiento pendiente'],
  'Tanques':['Falta de agua','Pérdida o filtración','Limpieza pendiente','Problema de presión'],
  'Fumigación':['Presencia de plagas','Servicio programado no realizado','Sector omitido','Reiteración del tratamiento'],
  'Limpieza':['Falta de limpieza','Insumos faltantes','Sector omitido','Servicio incompleto'],
  'Aires acondicionados':['Equipo no enciende','No funciona en frío','No funciona en calor','Pérdida de agua','Mantenimiento o filtros'],
  'Ascensores':['Ascensor fuera de servicio','Puertas no cierran','Indicador de piso defectuoso','Ruidos o movimientos anormales','Rescate o persona encerrada'],
  'Otro':['Servicio no prestado','Falla o funcionamiento deficiente','Mantenimiento pendiente','Incumplimiento del servicio']
};
const DEPENDENCIES = [
  ...Array.from({length:31},(_,i)=>`Juzgado Nacional de Primera Instancia en lo Comercial N.º ${i+1}`),
  ...['A','B','C','D','E','F'].map(x=>`Sala ${x}`),
  'Mesa de entradas','Portería','Jurisprudencia','Secretaría General','Habilitación','Superintendencia','Auxiliares de Justicia','Biblioteca','Intendencia','Otra dependencia'
];
const TEMPLATES = [
  {name:'Cambio de tubo de luz',category:'Electricidad',description:'Retirar el tubo agotado, verificar artefacto y reemplazar por uno operativo.'},
  {name:'Reparación o cambio de enchufe',category:'Electricidad',description:'Revisar el tomacorriente, ajustar conexiones y reemplazarlo si corresponde.'},
  {name:'Pérdida en canilla',category:'Sanitarios',description:'Revisar canilla, flexibles y cierre; reparar la pérdida y comprobar funcionamiento.'},
  {name:'Destapar desagote',category:'Sanitarios',description:'Desobstruir el desagote y verificar el escurrimiento correcto.'},
  {name:'Cambio de cerradura',category:'Carpintería',description:'Revisar y reemplazar cerradura; comprobar apertura y cierre.'},
  {name:'Ajuste de puerta',category:'Carpintería',description:'Alinear puerta, ajustar herrajes y comprobar cierre.'},
  {name:'Retoque de pintura',category:'Pintura',description:'Preparar la superficie y realizar retoque de pintura en el sector indicado.'},
  {name:'Revisión de aire acondicionado',category:'Aire acondicionado',description:'Verificar encendido, temperatura, filtros y desagote del equipo.'},
  {name:'Movimiento de mobiliario',category:'Movimiento interno',description:'Trasladar y ubicar el mobiliario según las indicaciones de la dependencia.'},
  {name:'Limpieza extraordinaria',category:'Limpieza',description:'Realizar limpieza puntual y retirar residuos del sector.'},
  ...[
    ['Cambio de lámpara LED','Electricidad'],['Cambio de interruptor','Electricidad'],['Revisión de artefacto de iluminación','Electricidad'],['Revisión de luz de emergencia','Electricidad'],['Reparación de timbre','Electricidad'],
    ['Cambio de flexible','Sanitarios'],['Reparación de descarga de inodoro','Sanitarios'],['Cambio de grifería','Sanitarios'],['Reparación de sifón','Sanitarios'],['Revisión de pérdida de agua','Sanitarios'],
    ['Ajuste de bisagras','Carpintería'],['Cambio de picaporte','Carpintería'],['Reparación de cajón','Carpintería'],['Reparación de escritorio','Carpintería'],['Colocación de estante','Carpintería'],
    ['Reparación de revoque','Albañilería'],['Reposición de baldosa','Albañilería'],['Sellado de filtración','Albañilería'],['Pintura de pared','Pintura'],['Pintura de puerta','Pintura'],
    ['Limpieza de filtros de aire','Aire acondicionado'],['Revisión de desagote de aire','Aire acondicionado'],['Reparación de silla','Tapicería'],['Retapizado de asiento','Tapicería'],
    ['Retiro de materiales','Movimiento interno'],['Colocación de cartelería','Mantenimiento general'],['Control de inventario','Administrativo'],['Carga de documentación','Administrativo'],['Seguimiento de proveedor','Administrativo'],['Preparación de pedido de insumos','Administrativo'],
    ['Coordinar visita del servicio de ascensores','Ascensores'],['Registrar falla de ascensor','Ascensores'],['Control de señalización de evacuación','Seguridad'],['Coordinar revisión del sistema de incendio','Seguridad']
  ].map(([name,category])=>({name,category,description:''}))
];
const seed = {people:[
  {id:'p1',name:'Carlos Benítez',role:'Ayudante',building:BUILDINGS[0]},
  {id:'p2',name:'Mariano Ferrante',role:'Ayudante',building:BUILDINGS[1]},
  {id:'p3',name:'Damián Morán',role:'Ayudante',building:BUILDINGS[2]},
  {id:'p4',name:'Laura Gómez',role:'Electricidad',building:BUILDINGS[0]},
  {id:'p5',name:'Diego Rodríguez',role:'Carpintería',building:BUILDINGS[1]},
  {id:'p6',name:'Javier Acosta',role:'Plomería',building:BUILDINGS[2]}
],tools:[
  {id:'H-0001',name:'Taladro percutor',type:'Herramienta eléctrica',brand:'Bosch',model:'GSB 13 RE',serial:'INV-001',toolStatus:'Entregada',holder:'p1',assignedDate:days(-12),notes:'Incluye mechas y maletín.',updatedAt:new Date().toISOString()},
  {id:'H-0002',name:'Multímetro digital',type:'Instrumento de medición',brand:'Uni-T',model:'UT33D+',serial:'INV-002',toolStatus:'Disponible',holder:'',assignedDate:'',notes:'',updatedAt:new Date().toISOString()}
],services:[
  {id:'S-0001',building:BUILDINGS[0],serviceType:'Ascensores',provider:'Prestador a completar',endDate:days(90),contactName:'',phone:'',email:'',notes:'',updatedAt:new Date().toISOString()}
],contacts:typeof OFFICIAL_CONTACTS==='undefined'?[]:structuredClone(OFFICIAL_CONTACTS),orders:[
  {id:'OT-0001',title:'Reparar pérdida de aire acondicionado',building:BUILDINGS[0],location:'9.º piso, oficina 914',category:'Aire acondicionado',specialty:'Aires Acondicionados',priority:'Alta',status:'En proceso',assignee:'p1',dueDate:days(1),description:'Revisar desagote y pérdida de agua.',createdAt:days(-3),updatedAt:new Date().toISOString()},
  {id:'OT-0002',title:'Revisar ascensor N.º 1',building:BUILDINGS[1],location:'Hall central',category:'Ascensores',specialty:'Electricidad',priority:'Urgente',status:'Pendiente',assignee:'',dueDate:days(-1),description:'Equipo fuera de servicio.',createdAt:days(-2),updatedAt:days(-1)},
  {id:'OT-0003',title:'Limpiar batea de desagote',building:BUILDINGS[0],location:'Portería',category:'Aire acondicionado',specialty:'Aires Acondicionados',priority:'Media',status:'Resuelto',assignee:'p1',dueDate:days(-1),description:'Batea sucia y obstruida.',createdAt:days(-5),updatedAt:days(-1)},
  {id:'OT-0004',title:'Verificar avisos del sistema SECURITON',building:BUILDINGS[2],location:'Central de incendio',category:'Seguridad',specialty:'Electricidad',priority:'Alta',status:'Sin asignar',assignee:'',dueDate:days(2),description:'Avisos recurrentes FALLA ELEM NO OK.',createdAt:days(-1),updatedAt:days(-1)}
]};
function days(offset){const d=new Date();d.setDate(d.getDate()+offset);return d.toISOString().slice(0,10)}
let state=structuredClone(seed);
let currentMessageOrderId='';
let appStarted=false, saveQueue=Promise.resolve(), lastRemoteUpdate='', remoteRevision=0, savePending=0;
function normalizeState(input){const value=input&&typeof input==='object'?input:{};value.people=Array.isArray(value.people)?value.people:[];value.orders=Array.isArray(value.orders)?value.orders:[];value.tools=Array.isArray(value.tools)?value.tools:[];value.services=Array.isArray(value.services)?value.services:[];value.contacts=Array.isArray(value.contacts)?value.contacts:[];const roleMap={'Mantenimiento general':'Ayudante','Servicios y traslados':'Ayudante','Patrimonio':'Carpintería','Sanitarios':'Plomería','Aire acondicionado':'Aires Acondicionados'};value.people.forEach(p=>{p.role=roleMap[p.role]||p.role;if(!SPECIALTIES.includes(p.role))p.role='Ayudante'});value.orders.forEach(o=>{if(!SPECIALTIES.includes(o.specialty))o.specialty=value.people.find(p=>p.id===o.assignee)?.role||CATEGORY_SPECIALTY[o.category]||'Ayudante'});return value}
function loadLegacy(){try{return normalizeState(JSON.parse(localStorage.getItem(STORE))||structuredClone(seed))}catch{return structuredClone(seed)}}
function save(){renderAll();const snapshot=structuredClone(state);savePending++;saveQueue=saveQueue.then(async()=>{const row=await db.saveState(snapshot,remoteRevision);lastRemoteUpdate=row?.updated_at||lastRemoteUpdate;remoteRevision=Number(row?.revision||remoteRevision)}).catch(async error=>{if(/REVISION_CONFLICT/.test(error.message)){const latest=await db.getState();if(latest){state=normalizeState(latest.data);lastRemoteUpdate=latest.updated_at;remoteRevision=Number(latest.revision||0);renderAll()}toast('Otro usuario modificó la información. Se cargó la versión más reciente.')}else toast(`No se guardó: ${error.message}`)}).finally(()=>savePending--);return saveQueue}
const $=s=>document.querySelector(s);
const slug=s=>s.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,'-');
const fmt=d=>d?new Intl.DateTimeFormat('es-AR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(d+'T12:00:00')):'Sin fecha';
const person=id=>state.people.find(p=>p.id===id);
const overdue=o=>o.status!=='Resuelto'&&o.dueDate&&o.dueDate<days(0);
function fillSelect(el,items,empty){el.innerHTML=(empty?`<option value="">${empty}</option>`:'')+items.map(x=>`<option value="${x}">${x}</option>`).join('')}
function init(){
  initModules();
  document.querySelectorAll('.nav-item').forEach(b=>b.onclick=()=>showView(b.dataset.view));
  document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));
  $('#logoutBtn').onclick=async()=>{await db.signOut();location.reload()};
  $('#newOrderBtn').onclick=()=>openOrder(); $('#newPersonBtn').onclick=()=>$('#personDialog').showModal();
  $('#newToolBtn').onclick=()=>openTool();
  $('#newServiceBtn').onclick=()=>openService(); $('#newContactBtn').onclick=()=>openContact(); $('#importContactsBtn').onclick=importOfficialContacts;
  document.querySelectorAll('.close-modal').forEach(b=>b.onclick=()=>$('#orderDialog').close());
  document.querySelectorAll('.close-person').forEach(b=>b.onclick=()=>$('#personDialog').close());
  document.querySelectorAll('.close-message').forEach(b=>b.onclick=()=>$('#messageDialog').close());
  document.querySelectorAll('.close-tool').forEach(b=>b.onclick=()=>$('#toolDialog').close());
  document.querySelectorAll('.close-service').forEach(b=>b.onclick=()=>$('#serviceDialog').close());
  document.querySelectorAll('.close-claim').forEach(b=>b.onclick=()=>$('#claimDialog').close());
  document.querySelectorAll('.close-contact').forEach(b=>b.onclick=()=>$('#contactDialog').close());
  $('#orderForm').onsubmit=submitOrder; $('#personForm').onsubmit=submitPerson;
  $('#deleteOrderBtn').onclick=deleteCurrentOrder; $('#finishOrderBtn').onclick=finishCurrentOrder;
  $('#toolForm').onsubmit=submitTool; $('#deleteToolBtn').onclick=deleteCurrentTool; $('#returnToolBtn').onclick=returnCurrentTool;
  $('#serviceForm').onsubmit=submitService; $('#deleteServiceBtn').onclick=deleteCurrentService;
  $('#contactForm').onsubmit=submitContact; $('#deleteContactBtn').onclick=deleteCurrentContact;
  ['searchInput','statusFilter','buildingFilter','specialtyFilter'].forEach(id=>$('#'+id).addEventListener('input',renderOrders));
  ['toolSearch','toolStatusFilter'].forEach(id=>$('#'+id).addEventListener('input',renderTools));
  $('#contactSearch').addEventListener('input',renderContacts);
  fillSelect($('#statusFilter'),STATUSES,'Todos los estados'); fillSelect($('#buildingFilter'),BUILDINGS,'Todos los edificios');
  fillSelect($('#orderForm [name=building]'),BUILDINGS); fillSelect($('#orderForm [name=priority]'),PRIORITIES); fillSelect($('#orderForm [name=status]'),STATUSES);
  fillSelect($('#personForm [name=building]'),BUILDINGS); renderAll();
  fillSelect($('#personForm [name=role]'),SPECIALTIES); fillSelect($('#specialtyFilter'),SPECIALTIES,'Todas las especialidades');
  fillSelect($('#serviceForm [name=building]'),BUILDINGS); fillSelect($('#serviceForm [name=serviceType]'),SERVICE_TYPES);
  fillSelect($('#contactForm [name=building]'),BUILDINGS,'Todos / sin edificio específico');
  $('#orderForm [name=building]').onchange=()=>refreshDependencies();
  refreshDependencies();
  fillSelect($('#orderForm [name=specialty]'),SPECIALTIES,'Seleccionar especialidad');
  $('#orderForm [name=specialty]').onchange=()=>refreshTaskOptions();
  refreshTaskOptions();
  $('#orderForm [name=template]').onchange=applyTemplate;
  $('#copyMessageBtn').onclick=copyMessage;
  $('#printOrderBtn').onclick=printCurrentOrder;
  $('#generateClaimBtn').onclick=generateClaimEmail; $('#copyClaimBtn').onclick=copyClaimEmail;
  $('#claimForm [name=reason]').onchange=generateClaimEmail; $('#claimForm [name=location]').oninput=generateClaimEmail; $('#claimForm [name=detail]').oninput=generateClaimEmail;
  $('#toolForm [name=holder]').onchange=e=>{const f=$('#toolForm');if(e.target.value){f.elements.toolStatus.value='Entregada';if(!f.elements.assignedDate.value)f.elements.assignedDate.value=days(0)}else if(f.elements.toolStatus.value==='Entregada'){f.elements.toolStatus.value='Disponible';f.elements.assignedDate.value=''}};
}
function showView(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$('#'+name+'View').classList.add('active');document.querySelectorAll('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#pageTitle').textContent={dashboard:'Panel general',orders:'Órdenes de trabajo',people:'Personal',tools:'Herramientas',services:'Servicios',contacts:'Contactos de utilidad',works:'Obras',guides:'Guías',reminders:'Recordatorios'}[name]}
function renderAll(){renderMetrics();renderBuildings();renderPriority();renderRecent();renderOrders();renderPeople();renderTools();renderServices();renderContacts();fillAssignees();fillToolHolders();renderModules()}
function renderMetrics(){const vals=[['Pendientes',state.orders.filter(o=>o.status==='Pendiente').length,'#d78a25'],['En proceso',state.orders.filter(o=>o.status==='En proceso').length,'#3157d5'],['Resueltos',state.orders.filter(o=>o.status==='Resuelto').length,'#16805b'],['Sin asignar',state.orders.filter(o=>!o.assignee||o.status==='Sin asignar').length,'#7650aa'],['Demorados',state.orders.filter(overdue).length,'#c64040']];$('#metrics').innerHTML=vals.map(v=>`<article class="metric"><div class="metric-top"><span>${v[0]}</span><span class="dot" style="background:${v[2]}"></span></div><b>${v[1]}</b></article>`).join('')}
function renderBuildings(){const max=Math.max(1,...BUILDINGS.map(b=>state.orders.filter(o=>o.building===b).length));$('#buildingSummary').innerHTML=BUILDINGS.map(b=>{const all=state.orders.filter(o=>o.building===b),active=all.filter(o=>o.status!=='Resuelto').length;return `<div class="building-row"><div><strong>${b}</strong><small>${active} activas · ${all.length-active} resueltas</small></div><div class="bar"><span style="width:${all.length/max*100}%"></span></div><b>${all.length}</b></div>`}).join('')}
function renderPriority(){const list=state.orders.filter(o=>o.priority==='Urgente'||overdue(o)||!o.assignee).slice(0,4);$('#priorityList').innerHTML=list.length?list.map(o=>`<div class="priority-card" data-open="${esc(o.id)}"><span class="badge priority-${slug(o.priority)}">${overdue(o)?'Demorada':esc(o.priority)}</span><div><strong>${esc(o.title)}</strong><small>${esc(o.building)} · ${esc(person(o.assignee)?.name||'Sin asignar')}</small></div></div>`).join(''):'<div class="empty">No hay órdenes prioritarias.</div>';bindOpen()}
function renderRecent(){const list=[...state.orders].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt))).slice(0,5);$('#recentOrders').innerHTML=table(list);bindOpen()}
function renderOrders(){const normalize=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const q=normalize($('#searchInput').value),status=$('#statusFilter').value,building=$('#buildingFilter').value,specialty=$('#specialtyFilter').value;const list=state.orders.filter(o=>(!status||o.status===status)&&(!building||o.building===building)&&(!specialty||o.specialty===specialty)&&normalize([o.id,o.title,o.description,o.dependency,o.building,o.category,o.location,person(o.assignee)?.name,o.specialty].join(' ')).includes(q)).sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));$('#ordersCount').textContent=`${list.length} resultado${list.length===1?'':'s'}`;$('#ordersTable').innerHTML=table(list);bindOpen()}
function table(list){if(!list.length)return '<div class="empty">No se encontraron órdenes.</div>';return `<div class="table-wrap"><table><thead><tr><th>Orden</th><th>Trabajo</th><th>Especialidad</th><th>Edificio</th><th>Responsable</th><th>Prioridad</th><th>Estado</th><th>Fecha límite</th></tr></thead><tbody>${list.map(o=>`<tr data-id="${esc(o.id)}"><td><strong>${esc(o.id)}</strong></td><td><strong>${esc(o.title)}</strong><small>${esc(o.dependency||'Dependencia sin especificar')} · ${esc(o.location)}</small></td><td>${esc(o.specialty||'Ayudante')}</td><td>${esc(o.building)}</td><td>${esc(person(o.assignee)?.name||'Sin asignar')}</td><td><span class="badge priority-${slug(o.priority)}">${esc(o.priority)}</span></td><td><span class="badge status-${slug(o.status)}">${esc(o.status)}</span></td><td>${esc(fmt(o.dueDate))}${overdue(o)?'<br><small class="expiry-soon">Demorada</small>':''}</td></tr>`).join('')}</tbody></table></div>`}
function renderPeople(){$('#peopleGrid').innerHTML=state.people.map(p=>{const active=state.orders.filter(o=>o.assignee===p.id&&o.status!=='Resuelto').length;const initials=p.name.split(' ').slice(0,2).map(x=>x[0]).join('');return `<article class="person-card"><div class="avatar">${esc(initials)}</div><div class="person-info"><strong>${esc(p.name)}</strong><small>${esc(p.role)}</small><small>${esc(p.building)}</small>${p.phone?`<small class="phone">WhatsApp: ${esc(p.phone)}</small>`:''}<span class="badge status-en-proceso" style="margin-top:9px">${active} tarea${active===1?'':'s'} activa${active===1?'':'s'}</span></div><button class="delete-person" data-delete-person="${esc(p.id)}" title="Eliminar empleado">Eliminar</button></article>`}).join('');document.querySelectorAll('[data-delete-person]').forEach(b=>b.onclick=()=>deletePerson(b.dataset.deletePerson))}
function fillPeopleSelect(s,empty){const value=s.value;s.replaceChildren();const first=document.createElement('option');first.value='';first.textContent=empty;s.append(first);state.people.forEach(p=>{const option=document.createElement('option');option.value=p.id;option.textContent=`${p.name} — ${p.role}`;s.append(option)});s.value=value}
function fillAssignees(){fillPeopleSelect($('#orderForm [name=assignee]'),'Sin asignar')}
function fillToolHolders(){fillPeopleSelect($('#toolForm [name=holder]'),'Sin entregar')}
function toggleCustomTask(){const f=$('#orderForm'),custom=f.elements.template.value==='Otra tarea';$('#customTaskLabel').hidden=!custom;f.elements.customTask.required=custom;f.elements.customTask.disabled=!custom}
function tasksForSpecialty(specialty){return TEMPLATES.filter(t=>(t.specialty||CATEGORY_SPECIALTY[t.category])===specialty)}
function refreshTaskOptions(title=''){const f=$('#orderForm'),specialty=f.elements.specialty.value,select=f.elements.template;fillSelect(select,specialty?[...tasksForSpecialty(specialty).map(t=>t.name),'Otra tarea']:[],specialty?'Seleccionar tarea':'Elegí primero una especialidad');select.value='';select.disabled=!specialty;if(title){select.value=tasksForSpecialty(specialty).some(t=>t.name===title)?title:'Otra tarea';f.elements.customTask.value=title}toggleCustomTask()}
function buildingForAddress(address){const s=String(address||'');if(/(?:Roque|Diagonal).*1211/i.test(s))return BUILDINGS[0];if(/Callao\s+635/i.test(s))return BUILDINGS[1];if(/Montevideo\s+546/i.test(s))return BUILDINGS[2];return ''}
function dependenciesForBuilding(building){if(!BUILDINGS.includes(building))return [];const catalog=typeof OFFICIAL_CONTACTS==='undefined'?[]:OFFICIAL_CONTACTS;const list=catalog.filter(c=>buildingForAddress(c.building)===building).map(c=>/^PJN-COM-J\d+$/.test(c.id)?`Juzgado N.º ${c.id.match(/\d+$/)[0]}`:c.id.startsWith('PJN-COM-SALA-')?`Sala ${c.id.slice(-1)}`:c.id==='PJN-COM-MESA-DIAGONAL'?null:c.id==='PJN-COM-AUXILIARES'?'Auxiliares de Justicia':c.name).filter(Boolean);return [...new Set([...list,'Portería','Otra dependencia'])]}
function canonicalDependency(value){return shortDependency(value)}
function refreshDependencies(previous=''){const f=$('#orderForm'),select=f.elements.dependency,list=dependenciesForBuilding(f.elements.building.value),value=canonicalDependency(previous);fillSelect(select,list,'Seleccionar dependencia');select.value='';select.disabled=!BUILDINGS.includes(f.elements.building.value);$('#dependencyWarning').hidden=true;if(value){if(!list.includes(value)){const option=document.createElement('option');option.value=value;option.textContent=`${value} (ubicación anterior: revisar)`;select.append(option);$('#dependencyWarning').hidden=false}select.value=value}}
function openOrder(id){const f=$('#orderForm');f.reset();fillAssignees();f.elements.id.value='';f.elements.specialty.value='';f.elements.status.value='Pendiente';f.elements.priority.value='Media';$('#orderModalTitle').textContent='Nueva orden';$('#deleteOrderBtn').style.display='none';$('#finishOrderBtn').style.display='none';let title='',dependency='';if(id){const o=state.orders.find(x=>x.id===id);if(!o)return;Object.entries(o).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});f.elements.specialty.value=SPECIALTIES.includes(o.specialty)?o.specialty:orderSpecialty(o);title=o.title||'';dependency=o.dependency||'';$('#orderModalTitle').textContent=`Editar ${o.id}`;$('#deleteOrderBtn').style.display='inline-block';$('#finishOrderBtn').style.display=o.status==='Resuelto'?'none':'inline-block'}refreshTaskOptions(title);refreshDependencies(dependency);$('#orderDialog').showModal()}
function orderSpecialty(data){return SPECIALTIES.includes(data.specialty)?data.specialty:CATEGORY_SPECIALTY[data.category]||person(data.assignee)?.role||'Ayudante'}
function submitOrder(e){
  e.preventDefault();
  const data=Object.fromEntries(new FormData(e.target)),now=new Date().toISOString();
  if(!SPECIALTIES.includes(data.specialty)){toast('Seleccioná una especialidad');return}
  if(data.template!=='Otra tarea'&&!tasksForSpecialty(data.specialty).some(t=>t.name===data.template)){toast('Seleccioná una tarea de esa especialidad');return}
  const previous=state.orders.find(o=>o.id===data.id),legacyMatch=previous&&previous.building===data.building&&canonicalDependency(previous.dependency)===data.dependency;
  if(!dependenciesForBuilding(data.building).includes(data.dependency)&&!legacyMatch){toast('Elegí una dependencia del edificio seleccionado');return}
  data.title=data.template==='Otra tarea'?(data.customTask||'').trim():data.template;
  if(!data.title){toast('Seleccioná una tarea');return}
  data.specialty=orderSpecialty(data);
  data.category=TEMPLATES.find(t=>t.name===data.template)?.category||Object.keys(CATEGORY_SPECIALTY).find(c=>CATEGORY_SPECIALTY[c]===data.specialty)||'Mantenimiento general';
  delete data.template;delete data.customTask;delete data.taskSpecialty;
  if(data.id){const i=state.orders.findIndex(o=>o.id===data.id);state.orders[i]={...state.orders[i],...data,updatedAt:now}}
  else{const n=Math.max(0,...state.orders.map(o=>Number(o.id.split('-')[1])))+1;data.id=`OT-${String(n).padStart(4,'0')}`;data.createdAt=now;data.updatedAt=now;state.orders.push(data)}
  save();$('#orderDialog').close();showAssignmentMessage(data);toast('Orden guardada correctamente');
}
function submitPerson(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id='p'+Date.now();state.people.push(data);save();e.target.reset();$('#personDialog').close();toast('Empleado agregado')}
function deletePerson(id){const p=person(id);if(!p||!confirm(`Eliminar a ${p.name}? Sus órdenes y herramientas quedarán sin asignar.`))return;state.orders.forEach(o=>{if(o.assignee===id){o.assignee='';o.status=o.status==='Resuelto'?'Resuelto':'Sin asignar';o.updatedAt=new Date().toISOString()}});state.tools.forEach(t=>{if(t.holder===id){t.holder='';t.assignedDate='';t.toolStatus='Disponible';t.updatedAt=new Date().toISOString()}});state.people=state.people.filter(x=>x.id!==id);save();toast('Empleado eliminado')}
function applyTemplate(e){toggleCustomTask();const f=$('#orderForm'),t=tasksForSpecialty(f.elements.specialty.value).find(x=>x.name===e.target.value);if(!t)return;f.elements.description.value=t.description}
function finishCurrentOrder(){const id=$('#orderForm [name=id]').value,o=state.orders.find(x=>x.id===id);if(!o||!confirm(`Marcar ${o.id} como finalizada?`))return;o.status='Resuelto';o.completedAt=new Date().toISOString();o.updatedAt=o.completedAt;save();$('#orderDialog').close();toast('Orden finalizada')}
function deleteCurrentOrder(){const id=$('#orderForm [name=id]').value,o=state.orders.find(x=>x.id===id);if(!o||!confirm(`Eliminar definitivamente la orden ${o.id}?`))return;state.orders=state.orders.filter(x=>x.id!==id);save();$('#orderDialog').close();toast('Orden eliminada')}
function shortDependency(value){const text=String(value||''),match=text.match(/juzgado.*?(?:N\.?\s*[.º°]*\s*|número\s*)(\d+)/i)||text.match(/juzgado\s+(\d+)/i);return match?`Juzgado N.º ${match[1]}`:text}
function assignmentText(o){const first=(person(o.assignee)?.name||'').trim().split(/\s+/)[0],building=String(o.building||'').replace('Diagonal Roque Sáenz Peña','Diagonal').replace('Av. Callao','Callao'),place=[building,shortDependency(o.dependency),o.location].filter(Boolean).join(', ');return `Hola${first?' '+first:''}, ¿podés encargarte de ${String(o.title||'esta tarea').replace(/^./,c=>c.toLowerCase())}?\n${place}.${o.dueDate?' Para el '+fmt(o.dueDate)+'.':''}${['Urgente','Alta'].includes(o.priority)?' '+(o.priority==='Urgente'?'Es urgente.':'Tiene prioridad.') :''}\nAvisame cuando esté listo. ¡Gracias! (${o.id})`}
function showAssignmentMessage(o){currentMessageOrderId=o.id;const msg=assignmentText(o),p=person(o.assignee),phone=(p?.phone||'').replace(/\D/g,''),button=$('#openWhatsappBtn');$('#whatsappMessage').value=msg;button.href=o.assignee?`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`:'#';button.classList.toggle('disabled',!o.assignee);button.setAttribute('aria-disabled',String(!o.assignee));$('#messageDialog').showModal()}
async function copyMessage(){await navigator.clipboard.writeText($('#whatsappMessage').value);toast('Mensaje copiado')}
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function printCurrentOrder(){const o=state.orders.find(x=>x.id===currentMessageOrderId);if(!o)return;const p=person(o.assignee),sheet=$('#printSheet');sheet.innerHTML=`<div class="print-header"><div><h1>ORDEN DE TRABAJO</h1><p>Intendencia — Cámara Nacional de Apelaciones en lo Comercial</p></div><div><span class="print-label">Número</span><strong>${esc(o.id)}</strong><br>Emitida: ${esc(fmt(o.createdAt?.slice(0,10)||days(0)))}</div></div><div class="print-grid"><div class="print-field"><span class="print-label">Edificio</span><strong>${esc(o.building)}</strong></div><div class="print-field"><span class="print-label">Dependencia</span><strong>${esc(o.dependency||'Sin especificar')}</strong></div><div class="print-field print-wide"><span class="print-label">Sector, oficina o puerta</span><strong>${esc(o.location)}</strong></div><div class="print-field print-wide"><span class="print-label">Trabajo solicitado</span><strong>${esc(o.title)}</strong></div><div class="print-field"><span class="print-label">Especialidad</span><strong>${esc(o.specialty)}</strong></div><div class="print-field"><span class="print-label">Prioridad</span><strong>${esc(o.priority)}</strong></div><div class="print-field"><span class="print-label">Responsable</span><strong>${esc(p?.name||'Sin asignar')}</strong></div><div class="print-field"><span class="print-label">Fecha límite</span><strong>${esc(fmt(o.dueDate))}</strong></div><div class="print-field print-wide print-description"><span class="print-label">Descripción e indicaciones</span>${esc(o.description||'Sin observaciones adicionales.')}</div></div><div class="print-tracking"><strong>Registro de ejecución</strong><div class="print-lines"><div class="print-line">Fecha y hora de inicio:</div><div class="print-line">Fecha y hora de finalización:</div><div class="print-line">Materiales utilizados:</div><div class="print-line">Observaciones:</div></div></div><div class="print-signatures"><div class="print-signature">Firma del responsable</div><div class="print-signature">Conformidad de la dependencia</div></div>`;window.print()}
function toolStatusClass(status){return {'Disponible':'tool-available','Entregada':'tool-assigned','En reparación':'tool-repair','Fuera de servicio':'tool-out'}[status]||''}
function renderTools(){const q=$('#toolSearch')?.value.toLowerCase()||'',filter=$('#toolStatusFilter')?.value||'',tools=state.tools||[];const visible=tools.filter(t=>(!filter||t.toolStatus===filter)&&[t.name,t.type,t.brand,t.model,t.serial,person(t.holder)?.name].join(' ').toLowerCase().includes(q));const counts=['Disponible','Entregada','En reparación','Fuera de servicio'].map(status=>[status,tools.filter(t=>t.toolStatus===status).length,{'Disponible':'#16805b','Entregada':'#3157d5','En reparación':'#bd7115','Fuera de servicio':'#c64040'}[status]]);if($('#toolMetrics'))$('#toolMetrics').innerHTML=counts.map(v=>`<article class="metric"><div class="metric-top"><span>${esc(v[0])}</span><span class="dot" style="background:${v[2]}"></span></div><b>${v[1]}</b></article>`).join('');if($('#toolsCount'))$('#toolsCount').textContent=`${visible.length} herramienta${visible.length===1?'':'s'}`;if(!$('#toolsTable'))return;$('#toolsTable').innerHTML=visible.length?`<div class="table-wrap"><table><thead><tr><th>ID</th><th>Herramienta</th><th>Marca / modelo</th><th>Identificación</th><th>Estado</th><th>Responsable</th><th>Entrega</th></tr></thead><tbody>${visible.map(t=>`<tr data-tool-id="${esc(t.id)}"><td><strong>${esc(t.id)}</strong></td><td><strong>${esc(t.name)}</strong><small>${esc(t.type)}</small></td><td>${esc(t.brand)}<br><small>${esc(t.model)}</small></td><td>${esc(t.serial||'Sin identificar')}</td><td><span class="badge ${toolStatusClass(t.toolStatus)}">${esc(t.toolStatus)}</span></td><td>${esc(person(t.holder)?.name||'—')}</td><td>${esc(fmt(t.assignedDate))}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No se encontraron herramientas.</div>';document.querySelectorAll('[data-tool-id]').forEach(row=>row.onclick=()=>openTool(row.dataset.toolId))}
function openTool(id){const f=$('#toolForm');f.reset();fillToolHolders();f.elements.id.value='';f.elements.toolStatus.value='Disponible';$('#toolModalTitle').textContent='Cargar herramienta';$('#deleteToolBtn').style.display='none';$('#returnToolBtn').hidden=true;$('#toolReturnHistory').innerHTML='';if(id){const t=state.tools.find(x=>x.id===id);if(!t)return;Object.entries(t).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$('#toolModalTitle').textContent=`Editar ${t.id}`;$('#deleteToolBtn').style.display='inline-block';$('#returnToolBtn').hidden=!t.holder;$('#toolReturnHistory').innerHTML=(Array.isArray(t.returns)?t.returns:[]).map(r=>`<p>Devuelta el ${esc(fmt(String(r.returnedAt||'').slice(0,10)))} por ${esc(r.holderName||'Empleado anterior')}.</p>`).join('')}$('#toolDialog').showModal()}
function registerToolReturn(t,now=new Date().toISOString()){if(!t.holder)return false;t.returns=Array.isArray(t.returns)?t.returns:[];t.returns.push({holder:t.holder,holderName:person(t.holder)?.name||'',assignedDate:t.assignedDate||'',returnedAt:now});t.holder='';t.assignedDate='';t.toolStatus='Disponible';t.returnedAt=now;t.updatedAt=now;return true}
function returnCurrentTool(){const t=state.tools.find(x=>x.id===$('#toolForm [name=id]').value);if(!t?.holder||!confirm(`¿Registrar la devolución de ${t.name}?`))return;registerToolReturn(t);save();$('#toolDialog').close();toast('Devolución registrada. Herramienta disponible')}
function submitTool(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),now=new Date().toISOString();if(!data.holder&&data.toolStatus==='Entregada')data.toolStatus='Disponible';if(data.holder&&data.toolStatus==='Disponible')data.toolStatus='Entregada';if(!data.holder)data.assignedDate='';if(data.id){const i=state.tools.findIndex(t=>t.id===data.id);state.tools[i]={...state.tools[i],...data,updatedAt:now}}else{const n=Math.max(0,...state.tools.map(t=>Number(t.id.split('-')[1])))+1;data.id=`H-${String(n).padStart(4,'0')}`;data.createdAt=now;data.updatedAt=now;state.tools.push(data)}save();$('#toolDialog').close();toast('Herramienta guardada')}
function deleteCurrentTool(){const id=$('#toolForm [name=id]').value,t=state.tools.find(x=>x.id===id);if(!t||!confirm(`Eliminar ${t.name} del inventario?`))return;state.tools=state.tools.filter(x=>x.id!==id);save();$('#toolDialog').close();toast('Herramienta eliminada')}
function renderServices(){const root=$('#servicesByBuilding');if(!root)return;root.innerHTML=BUILDINGS.map(building=>{const list=state.services.filter(s=>s.building===building);return `<section class="panel building-service-section"><div class="panel-head"><div><h2>${building}</h2><p>${list.length} servicio${list.length===1?'':'s'} cargado${list.length===1?'':'s'}</p></div></div><div class="service-grid">${list.length?list.map(serviceCard).join(''):'<div class="empty">No hay servicios cargados en este edificio.</div>'}</div></section>`}).join('');document.querySelectorAll('[data-edit-service]').forEach(b=>b.onclick=()=>openService(b.dataset.editService));document.querySelectorAll('[data-claim-service]').forEach(b=>b.onclick=()=>openClaim(b.dataset.claimService))}
function serviceCard(s){const expiring=s.endDate&&s.endDate<=days(30);return `<article class="service-card"><div class="service-card-head"><div><h3>${esc(s.serviceType)}</h3><p>${esc(s.provider)}</p></div><span class="badge ${expiring?'priority-urgente':'status-resuelto'}">${esc(s.endDate?'Hasta '+fmt(s.endDate):'Sin vencimiento')}</span></div><div class="service-contact"><p><strong>Contacto:</strong> ${esc(s.contactName||'Sin registrar')}</p><p><strong>Teléfono:</strong> ${esc(s.phone||'—')}</p><p><strong>Correo:</strong> ${esc(s.email||'—')}</p>${s.notes?`<p>${esc(s.notes)}</p>`:''}</div><div class="service-actions"><button class="edit-service" data-edit-service="${esc(s.id)}">Editar</button><button class="claim-button" data-claim-service="${esc(s.id)}">Generar reclamo</button></div></article>`}
function openService(id){const f=$('#serviceForm');f.reset();f.elements.id.value='';$('#serviceModalTitle').textContent='Cargar servicio';$('#deleteServiceBtn').style.display='none';if(id){const s=state.services.find(x=>x.id===id);Object.entries(s).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$('#serviceModalTitle').textContent=`Editar ${s.serviceType}`;$('#deleteServiceBtn').style.display='inline-block'}$('#serviceDialog').showModal()}
function submitService(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),now=new Date().toISOString();if(data.id){const i=state.services.findIndex(s=>s.id===data.id);state.services[i]={...state.services[i],...data,updatedAt:now}}else{const n=Math.max(0,...state.services.map(s=>Number(s.id.split('-')[1])))+1;data.id=`S-${String(n).padStart(4,'0')}`;data.createdAt=now;data.updatedAt=now;state.services.push(data)}save();$('#serviceDialog').close();toast('Servicio guardado')}
function deleteCurrentService(){const id=$('#serviceForm [name=id]').value,s=state.services.find(x=>x.id===id);if(!s||!confirm(`Eliminar el servicio ${s.serviceType} de ${s.building}?`))return;state.services=state.services.filter(x=>x.id!==id);save();$('#serviceDialog').close();toast('Servicio eliminado')}
function openClaim(id){const s=state.services.find(x=>x.id===id),f=$('#claimForm');f.reset();f.elements.serviceId.value=id;$('#claimTitle').textContent=`Reclamo — ${s.serviceType}`;fillSelect(f.elements.reason,CLAIM_REASONS[s.serviceType]||CLAIM_REASONS.Otro);generateClaimEmail();$('#claimDialog').showModal()}
function generateClaimEmail(e){e?.preventDefault();const f=$('#claimForm'),s=state.services.find(x=>x.id===f.elements.serviceId.value);if(!s)return;const reason=f.elements.reason.value||'inconveniente en el servicio',location=f.elements.location.value||'[indicar ubicación]',detail=f.elements.detail.value.trim();$('#claimEmail').value=`Asunto: Solicitud de intervención — ${s.serviceType} — ${s.building}\n\nPor medio del presente, se solicita la intervención de esa empresa a fin de subsanar el siguiente inconveniente relacionado con el servicio de ${s.serviceType.toLowerCase()}: ${reason.toLowerCase()}.\n\nEl inconveniente se presenta en el edificio sito en ${s.building}, específicamente en ${location}.${detail?` Se deja constancia de que ${detail}`:''}\n\nEn virtud de lo expuesto, se requiere arbitrar los medios necesarios para efectuar la correspondiente revisión y reparación a la mayor brevedad posible, informando fecha y horario estimados de concurrencia.\n\nAsimismo, se solicita comunicar el diagnóstico y las tareas realizadas una vez finalizada la intervención.\n\nSin otro particular, saludo atentamente.\n\nIntendencia\nCámara Nacional de Apelaciones en lo Comercial`}
async function copyClaimEmail(e){e?.preventDefault();await navigator.clipboard.writeText($('#claimEmail').value);toast('Correo copiado')}
function contactMatches(c,q){const normalize=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9@]+/g,' ');const text=normalize([c.name,c.organization,c.role,c.building,c.phone,c.email,c.notes].join(' '));return normalize(q).trim().split(/\s+/).filter(Boolean).every(word=>text.includes(word))}
function mergeOfficialContacts(existing,catalog){const ids=new Set(existing.map(c=>c.id)),emails=new Set(existing.map(c=>String(c.email||'').trim().toLowerCase()).filter(Boolean));const additions=catalog.filter(c=>!ids.has(c.id)&&!emails.has(String(c.email||'').trim().toLowerCase()));existing.push(...structuredClone(additions));return additions.length}
function importOfficialContacts(){const count=mergeOfficialContacts(state.contacts,OFFICIAL_CONTACTS);if(count){save();toast(`${count} contactos oficiales agregados`)}else toast('Los contactos oficiales ya están cargados')}
function renderContacts(){const q=$('#contactSearch')?.value||'',list=state.contacts.filter(c=>contactMatches(c,q));if($('#contactsCount'))$('#contactsCount').textContent=`${list.length} contacto${list.length===1?'':'s'}`;if(!$('#contactsTable'))return;$('#contactsTable').innerHTML=list.length?`<div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Entidad</th><th>Función / rubro</th><th>Dirección / edificio</th><th>Teléfono</th><th>Correo</th></tr></thead><tbody>${list.map(c=>`<tr data-contact-id="${esc(c.id)}"><td><strong>${esc(c.name)}</strong>${c.source==='https://www.pjn.gov.ar/guia'?'<small>Fuente: Guía PJN · 16/09/2026</small>':''}</td><td>${esc(c.organization||'—')}</td><td>${esc(c.role)}</td><td>${esc(c.building||'Todos')}</td><td>${esc(c.phone||'—')}</td><td>${esc(c.email||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No se encontraron contactos. Podés agregar uno o cargar el catálogo oficial.</div>';document.querySelectorAll('[data-contact-id]').forEach(row=>row.onclick=()=>openContact(row.dataset.contactId))}
function openContact(id){const f=$('#contactForm');f.reset();fillSelect(f.elements.building,BUILDINGS,'Todos / sin edificio específico');f.elements.id.value='';$('#contactModalTitle').textContent='Agregar contacto';$('#deleteContactBtn').style.display='none';if(id){const c=state.contacts.find(x=>x.id===id);if(!c)return;if(c.building&&!BUILDINGS.includes(c.building)){const option=document.createElement('option');option.value=c.building;option.textContent=c.building;f.elements.building.append(option)}Object.entries(c).forEach(([k,v])=>{if(f.elements[k])f.elements[k].value=v});$('#contactModalTitle').textContent=`Editar ${c.name}`;$('#deleteContactBtn').style.display='inline-block'}$('#contactDialog').showModal()}
function submitContact(e){e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),now=new Date().toISOString();if(data.id){const i=state.contacts.findIndex(c=>c.id===data.id);state.contacts[i]={...state.contacts[i],...data,updatedAt:now}}else{data.id=`C-${Date.now()}`;data.createdAt=now;data.updatedAt=now;state.contacts.push(data)}save();$('#contactDialog').close();toast('Contacto guardado')}
function deleteCurrentContact(){const id=$('#contactForm [name=id]').value,c=state.contacts.find(x=>x.id===id);if(!c||!confirm(`Eliminar el contacto ${c.name}?`))return;state.contacts=state.contacts.filter(x=>x.id!==id);save();$('#contactDialog').close();toast('Contacto eliminado')}
function bindOpen(){document.querySelectorAll('[data-id],[data-open]').forEach(el=>el.onclick=()=>openOrder(el.dataset.id||el.dataset.open))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function startApplication(user){$('#authScreen').classList.add('hidden');$('#sessionEmail').textContent=user.email||'Usuario autorizado';try{const remote=await db.getState();if(remote?.data){state=normalizeState(remote.data);lastRemoteUpdate=remote.updated_at||'';remoteRevision=Number(remote.revision||0)}else{state=loadLegacy();const created=await db.saveState(state,0);lastRemoteUpdate=created?.updated_at||'';remoteRevision=Number(created?.revision||1);localStorage.removeItem(STORE)}if(!appStarted){init();appStarted=true}else renderAll();setInterval(syncRemote,15000)}catch(error){$('#authScreen').classList.remove('hidden');$('#loginError').textContent=`No se pudo cargar la base: ${error.message}`}}
async function syncRemote(){if(savePending)return;try{const remote=await db.getState();if(remote?.revision&&Number(remote.revision)!==remoteRevision){state=normalizeState(remote.data);lastRemoteUpdate=remote.updated_at;remoteRevision=Number(remote.revision);renderAll();toast('Información actualizada')}}catch(error){if(/sesión/i.test(error.message))location.reload()}}
async function bootstrap(){const configured=db.configure(window.APP_CONFIG);const form=$('#loginForm'),warning=$('#configWarning');warning.classList.toggle('show',!configured);form.querySelector('button[type=submit]').disabled=!configured;form.onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';const button=form.querySelector('button[type=submit]');button.disabled=true;button.textContent='Ingresando…';try{const values=Object.fromEntries(new FormData(form));const user=await db.signIn(APP_CONFIG.MASTER_EMAIL,values.password);form.reset();await startApplication(user)}catch(error){$('#loginError').textContent=error.message}finally{button.disabled=false;button.textContent='Ingresar'}};if(configured){const user=await db.ensureSession();if(user)await startApplication(user)}}
bootstrap();
