'use strict';
const MODULES={works:'Obras',guides:'Guías',reminders:'Recordatorios'};
const money=value=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(Number(value)||0);
function ensureModules(){for(const key of Object.keys(MODULES))if(!Array.isArray(state[key]))state[key]=[]}
function moduleField(name,title,type='text',options=[]){if(type==='select')return `<label>${title}<select name="${name}">${options.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label>`;if(type==='textarea')return `<label class="wide">${title}<textarea name="${name}" rows="5" maxlength="10000" required></textarea></label>`;return `<label>${title}<input name="${name}" type="${type}" ${['name','date','startDate','dueDate'].includes(name)?'required':''} ${type==='number'?'min="0" step="0.01"':'maxlength="250"'}></label>`}
function initModules(){
  ensureModules();
  const nav=document.querySelector('.sidebar nav'),main=document.querySelector('main');
  for(const [key,title] of Object.entries(MODULES)){
    nav.insertAdjacentHTML('beforeend',`<button class="nav-item" data-view="${key}">${title}</button>`);
    main.insertAdjacentHTML('beforeend',`<section id="${key}View" class="view"><div class="people-header"><p>${key==='works'?'Registro de obras y montos en pesos argentinos.':key==='guides'?'Instrucciones internas paso a paso.':'Notas programadas con aviso el día anterior y el mismo día.'}</p><button class="secondary" id="add-${key}">+ Agregar</button></div>${key==='works'?'<div class="panel module-filters"><label>Mes<select id="worksMonth"><option value="">Todos</option>'+Array.from({length:12},(_,i)=>`<option value="${String(i+1).padStart(2,'0')}">${new Intl.DateTimeFormat('es-AR',{month:'long'}).format(new Date(2026,i,1))}</option>`).join('')+'</select></label><label>Año<select id="worksYear"><option value="">Todos</option></select></label><div><small>Total según período seleccionado</small><h2 id="worksTotal"></h2></div><div><small>Total general de obras</small><h2 id="worksGrandTotal"></h2></div></div>':''}<div id="${key}List" class="module-list"></div></section>`);
    let fields=key==='works'?moduleField('name','Nombre de la obra')+moduleField('building','Edificio','select',BUILDINGS)+moduleField('date','Fecha para el cómputo mensual','date')+moduleField('startDate','Inicio previsto','date')+moduleField('endDate','Fin previsto / plazo','date')+moduleField('amount','Monto de la obra (ARS)','number')+moduleField('purchaseOrder','Orden de compra')+moduleField('company','Empresa ejecutora')+moduleField('status','Estado','select',['Pronta','En progreso','Realizada']):key==='guides'?moduleField('name','Título de la guía')+moduleField('specialty','Especialidad','select',SPECIALTIES)+moduleField('steps','Pasos: escribí un paso por línea','textarea'):moduleField('name','Título del recordatorio')+moduleField('dueDate','Fecha programada','date')+moduleField('time','Hora de referencia','time')+moduleField('repeat','Repetición','select',['No repetir','Semanal','Mensual','Anual'])+moduleField('notes','Nota','textarea');
    document.body.insertAdjacentHTML('beforeend',`<dialog id="${key}Dialog"><form id="${key}Form"><div class="modal-head"><h2>${title}</h2><button type="button" class="icon-btn" data-close-module="${key}">×</button></div><input name="id" type="hidden"><div class="form-grid">${fields}</div><div class="modal-actions"><button type="button" class="danger" id="delete-${key}">Eliminar</button><span class="action-spacer"></span><button type="submit" class="primary">Guardar</button></div></form></dialog>`);
    document.getElementById('add-'+key).onclick=()=>openModule(key);
    document.querySelector(`[data-close-module="${key}"]`).onclick=()=>document.getElementById(key+'Dialog').close();
    document.getElementById(key+'Form').onsubmit=async e=>{e.preventDefault();const f=e.target;if(!f.reportValidity())return;const data=Object.fromEntries(new FormData(f));if(key==='works'){data.amount=Number(data.amount);if(!Number.isFinite(data.amount)||data.amount<0){toast('Monto inválido');return}if(data.endDate&&data.endDate<data.startDate){toast('El fin no puede ser anterior al inicio');return}}data.updatedAt=new Date().toISOString();if(data.id){const index=state[key].findIndex(v=>v.id===data.id);if(index<0)return;state[key][index]={...state[key][index],...data}}else{data.id=crypto.randomUUID();state[key].push(data)}document.getElementById(key+'Dialog').close();await save()};
    document.getElementById('delete-'+key).onclick=async()=>{const id=document.getElementById(key+'Form').elements.id.value;if(id&&confirm('Eliminar este registro definitivamente?')){state[key]=state[key].filter(v=>v.id!==id);document.getElementById(key+'Dialog').close();await save()}};
  }
  for(const id of ['worksMonth','worksYear'])document.getElementById(id).onchange=renderModules;
  document.body.insertAdjacentHTML('beforeend','<dialog id="guideReader"><div class="modal-head"><h2 id="guideReaderTitle"></h2><button class="icon-btn" id="closeGuideReader">×</button></div><ol id="guideReaderSteps" class="guide-steps"></ol></dialog><dialog id="reminderAlert"><div class="modal-head"><h2>Recordatorios próximos</h2><button class="icon-btn" id="closeReminderAlert">×</button></div><div id="reminderAlertList" class="message-body"></div><div class="modal-actions"><button class="primary" id="ackReminderAlert">Entendido</button></div></dialog>');
  document.getElementById('closeGuideReader').onclick=()=>document.getElementById('guideReader').close();
  const dismiss=()=>{document.getElementById('reminderAlert').close();sessionStorage.setItem('reminders-seen-'+localDate(new Date()),'1')};
  document.getElementById('closeReminderAlert').onclick=dismiss;document.getElementById('ackReminderAlert').onclick=dismiss;
  setTimeout(checkReminderAlerts,500);setInterval(checkReminderAlerts,60000);
}
function openModule(key,id){ensureModules();const f=document.getElementById(key+'Form');f.reset();f.elements.id.value='';if(key==='works'){f.elements.date.value=localDate(new Date());f.elements.startDate.value=localDate(new Date())}if(id){const record=state[key].find(v=>v.id===id);if(!record)return;for(const [name,value]of Object.entries(record))if(f.elements[name])f.elements[name].value=value}document.getElementById('delete-'+key).hidden=!id;document.getElementById(key+'Dialog').showModal()}
function renderModules(){ensureModules();if(!document.getElementById('worksList'))return;
  const yearSelect=document.getElementById('worksYear'),previousYear=yearSelect.value,years=[...new Set(state.works.map(w=>(w.date||'').slice(0,4)).filter(Boolean))].sort().reverse();yearSelect.replaceChildren(new Option('Todos',''),...years.map(y=>new Option(y,y)));yearSelect.value=previousYear;
  const month=document.getElementById('worksMonth').value,year=yearSelect.value,works=state.works.filter(w=>(!month||(w.date||'').slice(5,7)===month)&&(!year||(w.date||'').slice(0,4)===year));
  document.getElementById('worksTotal').textContent=money(works.reduce((sum,w)=>sum+Number(w.amount||0),0));document.getElementById('worksGrandTotal').textContent=money(state.works.reduce((sum,w)=>sum+Number(w.amount||0),0));
  document.getElementById('worksList').innerHTML=works.map(w=>`<article class="panel module-card"><div class="panel-head"><h2>${esc(w.name)}</h2><span class="badge ${w.status==='Realizada'?'status-resuelto':'status-en-proceso'}">${esc(w.status)}</span></div><p>${esc(w.building)} · ${esc(w.company||'Empresa sin registrar')}</p><h2>${money(w.amount)}</h2><p>Período: ${esc(fmt(w.date))}<br>Plazo: ${esc(fmt(w.startDate))} al ${esc(fmt(w.endDate))}<br>Orden de compra: ${esc(w.purchaseOrder||'—')}</p><button class="secondary" data-edit-works="${esc(w.id)}">Editar obra</button></article>`).join('')||'<div class="empty">No hay obras para este período.</div>';
  document.getElementById('guidesList').innerHTML=state.guides.map(g=>`<article class="panel module-card"><h2>${esc(g.name)}</h2><p>${esc(g.specialty)} · ${String(g.steps||'').split('\n').filter(s=>s.trim()).length} pasos</p><div class="service-actions"><button class="primary" data-read-guide="${esc(g.id)}">Consultar guía</button><button class="secondary" data-edit-guides="${esc(g.id)}">Editar</button></div></article>`).join('')||'<div class="empty">No hay guías cargadas.</div>';
  document.getElementById('remindersList').innerHTML=state.reminders.map(r=>`<article class="panel module-card"><h2>${esc(r.name)}</h2><p>Programado: ${esc(fmt(r.dueDate))} ${esc(r.time||'')} · ${esc(r.repeat||'No repetir')}</p><p class="note-text">${esc(r.notes)}</p><button class="secondary" data-edit-reminders="${esc(r.id)}">Editar recordatorio</button></article>`).join('')||'<div class="empty">No hay recordatorios programados.</div>';
  for(const key of Object.keys(MODULES))document.querySelectorAll(`[data-edit-${key}]`).forEach(b=>b.onclick=()=>openModule(key,b.getAttribute('data-edit-'+key)));
  document.querySelectorAll('[data-read-guide]').forEach(b=>b.onclick=()=>{const g=state.guides.find(v=>v.id===b.dataset.readGuide);document.getElementById('guideReaderTitle').textContent=g.name;document.getElementById('guideReaderSteps').innerHTML=String(g.steps||'').split('\n').filter(s=>s.trim()).map(s=>`<li>${esc(s)}</li>`).join('');document.getElementById('guideReader').showModal()});
}
function localDate(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function isReminderOccurrence(r,target){if(!/^\d{4}-\d{2}-\d{2}$/.test(r.dueDate||''))return false;const base=new Date(r.dueDate+'T12:00:00'),d=new Date(target+'T12:00:00');if(d<base)return false;if(r.repeat==='Semanal')return (Date.UTC(d.getFullYear(),d.getMonth(),d.getDate())-Date.UTC(base.getFullYear(),base.getMonth(),base.getDate()))/86400000%7===0;if(r.repeat==='Mensual')return d.getDate()===Math.min(base.getDate(),new Date(d.getFullYear(),d.getMonth()+1,0).getDate());if(r.repeat==='Anual')return d.getMonth()===base.getMonth()&&d.getDate()===Math.min(base.getDate(),new Date(d.getFullYear(),d.getMonth()+1,0).getDate());return target===r.dueDate}
function checkReminderAlerts(){if(!document.getElementById('reminderAlert')||!document.getElementById('authScreen').classList.contains('hidden'))return;ensureModules();const now=new Date(),today=localDate(now);if(sessionStorage.getItem('reminders-seen-'+today))return;const next=new Date(now);next.setDate(next.getDate()+1);const tomorrow=localDate(next),items=state.reminders.flatMap(r=>[today,tomorrow].filter(d=>isReminderOccurrence(r,d)).map(d=>({r,d})));if(!items.length)return;const dialog=document.getElementById('reminderAlert');if(dialog.open||document.querySelector('dialog[open]'))return;document.getElementById('reminderAlertList').innerHTML=items.map(({r,d})=>`<article class="reminder-item"><span class="badge ${d===today?'priority-urgente':'status-en-proceso'}">${d===today?'Hoy':'Mañana'} ${esc(r.time||'')}</span><h3>${esc(r.name)}</h3><p class="note-text">${esc(r.notes)}</p></article>`).join('');dialog.showModal()}
