'use strict';
const SUPPLY_DEFAULTS=[['a4','Resmas de papel A4','resmas',10],['yellow','Carátulas amarillas','unidades',1],['blue','Carátulas azules','unidades',1],['green','Carpetas verdes','unidades',1],['small','Sobres chicos','unidades',1],['large','Sobres grandes','unidades',1]];
let selectedSupplyDepot=0,supplySearch='',showArchivedSupplies=false;
function editSupplyProduct(s,id,name,unit,quantity){const p=s.products.find(p=>p.id===id),clean=String(name||'').trim(),cleanUnit=String(unit||'').trim();if(!p)throw Error('No se encontró el insumo.');if(!clean||clean.length>100||!cleanUnit||cleanUnit.length>30)throw Error('Revisá el nombre y la unidad.');if(s.products.some(x=>x.id!==id&&normalizeContactText(x.name)===normalizeContactText(clean)))throw Error('Ese nombre ya existe.');const amount=supplyAmount(quantity);if(cleanUnit!==p.unit&&(p.id==='a4'||s.movements.some(m=>m.product===id)||Object.values(s.depots).some(d=>d.stock[id]>0)))throw Error('No se puede cambiar la unidad de un insumo con stock o movimientos. Podés agregar otro insumo.');Object.assign(p,{name:clean,unit:cleanUnit,defaultQuantity:amount,updatedAt:new Date().toISOString()});return p}
function archiveSupplyProduct(s,id){const p=s.products.find(p=>p.id===id);if(!p)throw Error('No se encontró el insumo.');if(s.assignments.some(a=>a.product===id&&a.status==='Pendiente'))throw Error('Primero marcá como retiradas o cancelá las entregas pendientes de este insumo.');p.archived=true;p.updatedAt=new Date().toISOString()}
function restoreSupplyProduct(s,id){const p=s.products.find(p=>p.id===id);if(!p)throw Error('No se encontró el insumo.');p.archived=false;p.updatedAt=new Date().toISOString()}
function visibleSupplyProducts(s){return s.products.filter(p=>(showArchivedSupplies||!p.archived)&&normalizeContactText(p.name).includes(normalizeContactText(supplySearch)))}
function openSupplyProduct(id){const s=ensureSupplies(),f=$('#supplyProductForm');f.reset();f.elements.id.value=id||'';$('#supplyProductTitle').textContent=id?'Editar insumo':'Agregar insumo';$('#saveSupplyProduct').textContent=id?'Guardar cambios':'Agregar a los tres depósitos';if(id){const p=s.products.find(p=>p.id===id);if(!p)return;f.elements.name.value=p.name;f.elements.unit.value=p.unit;f.elements.quantity.value=p.defaultQuantity}$('#supplyProductDialog').showModal()}
function ensureSupplies(workspace=state){
  if(!workspace.supplies||typeof workspace.supplies!=='object'||Array.isArray(workspace.supplies))workspace.supplies={};
  const s=workspace.supplies;
  for(const key of ['products','assignments','movements','reports'])if(!Array.isArray(s[key]))s[key]=[];
  if(!s.depots||typeof s.depots!=='object'||Array.isArray(s.depots))s.depots={};
  if(!s.initialized){for(const [id,name,unit,defaultQuantity]of SUPPLY_DEFAULTS)if(!s.products.some(p=>p.id===id))s.products.push({id,name,unit,defaultQuantity});s.initialized=true}
  for(const building of BUILDINGS){if(!s.depots[building])s.depots[building]={referee:'',stock:{}};const d=s.depots[building];if(!d.stock||typeof d.stock!=='object')d.stock={};for(const p of s.products)if(!Object.hasOwn(d.stock,p.id))d.stock[p.id]=0}
  return s;
}
function supplyToday(now=new Date()){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Argentina/Buenos_Aires',year:'numeric',month:'2-digit',day:'2-digit'}).format(now)}
function supplyWednesday(date){if(!/^\d{4}-\d{2}-\d{2}$/.test(date||''))return false;const d=new Date(date+'T12:00:00Z');return !Number.isNaN(d.getTime())&&d.toISOString().slice(0,10)===date&&d.getUTCDay()===3}
function nextSupplyWednesday(now=new Date()){
  const today=supplyToday(now),d=new Date(today+'T12:00:00Z');let offset=(3-d.getUTCDay()+7)%7;
  const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'America/Argentina/Buenos_Aires',hour:'2-digit',hourCycle:'h23'}).format(now));
  if(offset===0&&hour>=8)offset=7;d.setUTCDate(d.getUTCDate()+offset);return d.toISOString().slice(0,10);
}
function supplyAmount(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw Error('La cantidad debe ser un número entero mayor que cero.');return n}
function supplyStock(s,building,product){const value=Number(s.depots[building]?.stock[product]);if(!Number.isSafeInteger(value)||value<0)throw Error('El stock no es válido. Revisá el depósito.');return value}
function supplyMovement(s,building,product,delta,reason,assignmentId=''){
  const before=supplyStock(s,building,product),after=before+delta;
  if(!Number.isSafeInteger(delta)||!Number.isSafeInteger(after)||after<0)throw Error('No hay stock suficiente o la cantidad no es válida.');
  s.depots[building].stock[product]=after;
  s.movements.push({id:crypto.randomUUID(),building,product,delta,before,after,reason,assignmentId,createdAt:new Date().toISOString()});
}
function addSupplyProduct(s,name,unit,quantity){const clean=String(name||'').trim();if(!clean||clean.length>100)throw Error('Ingresá un nombre de hasta 100 caracteres.');if(s.products.some(p=>normalizeContactText(p.name)===normalizeContactText(clean)))throw Error('Ese insumo ya existe.');const product={id:crypto.randomUUID(),name:clean,unit:String(unit||'unidades').trim().slice(0,30)||'unidades',defaultQuantity:supplyAmount(quantity)};s.products.push(product);for(const d of Object.values(s.depots))d.stock[product.id]=0;return product}
function assignSupply(s,{building,dependency,product,quantity,pickupDate}){
  if(!BUILDINGS.includes(building)||!dependenciesForBuilding(building).includes(dependency))throw Error('Elegí una dependencia del depósito seleccionado.');
  if(!s.products.some(p=>p.id===product&&!p.archived))throw Error('Elegí un insumo activo.');
  if(!supplyWednesday(pickupDate))throw Error('La fecha de retiro debe ser un miércoles.');
  const amount=supplyAmount(quantity),id=crypto.randomUUID();
  supplyMovement(s,building,product,-amount,'Asignación / reserva',id);
  const record={id,building,dependency,product,quantity:amount,pickupDate,status:'Pendiente',createdAt:new Date().toISOString()};s.assignments.push(record);return record;
}
function changeSupplyStatus(s,id,status){const a=s.assignments.find(a=>a.id===id);if(!a||a.status!=='Pendiente')throw Error('Esta asignación ya fue resuelta.');if(!['Retirado','Cancelado'].includes(status))throw Error('Estado inválido.');if(status==='Cancelado')supplyMovement(s,a.building,a.product,a.quantity,'Cancelación: devolución al stock',a.id);a.status=status;a.updatedAt=new Date().toISOString()}
function pendingSupplyAssignments(s,building,date){return s.assignments.filter(a=>a.building===building&&a.status==='Pendiente'&&a.pickupDate<=date)}
function supplyDependencyLabel(value){const court=/juzgado.*?(\d+)/i.exec(value||'');if(court)return court[1];const sala=/^Sala\s+([A-F])$/i.exec(value||'');if(sala)return sala[1].toUpperCase();if(/^Mesa\s/i.test(value||''))return 'Mesa de entradas';return value}
function supplyReportText(assignments){const deps=[...new Set(assignments.map(a=>supplyDependencyLabel(a.dependency)))].sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true}));if(!deps.length)throw Error('No hay retiros pendientes para informar.');const courts=deps.some(d=>/^\d+$/.test(d)),salas=deps.some(d=>/^[A-F]$/.test(d)),others=deps.some(d=>!/^\d+$|^[A-F]$/.test(d));const label=others?'las siguientes dependencias':courts?(salas?'los siguientes juzgados y salas':'los siguientes juzgados'):'las siguientes salas';return `Buenos días, hoy pasan a retirar ${label}: ${deps.join('-')}.\nAvisame mañana los que retiraron. Gracias!`}
function initSupplies(){
  ensureSupplies();
  document.querySelector('.sidebar nav').insertAdjacentHTML('beforeend','<button class="nav-item" data-view="supplies">Insumos</button>');
  document.querySelector('main').insertAdjacentHTML('beforeend','<section id="suppliesView" class="view"><div class="people-header"><div><p>Depósitos, stock disponible y retiros de los miércoles.</p><p>Asignar descuenta y reserva. Marcar Retirado no descuenta otra vez; cancelar devuelve el stock.</p></div><button class="secondary" id="newSupplyProduct">+ Agregar insumo</button></div><div class="supply-workspace-toolbar"><div id="supplyDepotTabs" class="supply-tabs" role="group" aria-label="Seleccionar depósito"></div><input id="supplyCatalogSearch" type="search" aria-label="Buscar insumos" placeholder="Buscar insumo"><label class="supply-archive-toggle"><input id="showArchivedSupplies" type="checkbox"> Ver dados de baja</label></div><div id="supplySummary" class="supply-summary"></div><div id="supplyDepots" class="supply-depots"></div><section class="panel"><div class="panel-head"><h2>Movimientos de stock</h2></div><div id="supplyMovements"></div></section></section>');
  document.body.insertAdjacentHTML('beforeend',`<dialog id="supplyDialog"><form id="supplyForm"><div class="modal-head"><h2>Asignar insumos</h2><button type="button" class="icon-btn" data-close-supply="supplyDialog">×</button></div><input name="building" type="hidden"><div class="form-grid"><label>Dependencia<select name="dependency" required></select></label><label>Insumo<select name="product" required></select></label><label>Cantidad<input name="quantity" type="number" min="1" step="1" required></label><label>Miércoles de retiro<input name="pickupDate" type="date" required></label><p id="supplyStockHint" class="security-note wide"></p></div><div class="modal-actions"><button class="primary" type="submit">Asignar y descontar stock</button></div></form></dialog>
  <dialog id="supplyProductDialog"><form id="supplyProductForm"><div class="modal-head"><h2 id="supplyProductTitle">Agregar insumo</h2><button type="button" class="icon-btn" data-close-supply="supplyProductDialog">×</button></div><input name="id" type="hidden"><div class="form-grid"><label class="wide">Nombre<input name="name" maxlength="100" required></label><label>Unidad<input name="unit" value="unidades" maxlength="30" required></label><label>Cantidad sugerida por entrega<input name="quantity" type="number" min="1" step="1" value="1" required></label></div><div class="modal-actions"><button class="primary" id="saveSupplyProduct">Agregar a los tres depósitos</button></div></form></dialog>
  <dialog id="supplyStockDialog"><form id="supplyStockForm"><div class="modal-head"><h2>Actualizar stock</h2><button type="button" class="icon-btn" data-close-supply="supplyStockDialog">×</button></div><input name="building" type="hidden"><input name="product" type="hidden"><div class="form-grid"><p id="supplyStockTitle" class="wide"></p><label>Operación<select name="operation"><option value="add">Ingreso / reposición</option><option value="set">Corregir stock disponible</option></select></label><label>Cantidad<input name="quantity" type="number" min="0" step="1" required></label><label class="wide">Motivo<input name="reason" maxlength="200" required placeholder="Ej.: carga inicial, compra, recuento"></label><p class="security-note wide">El papel se cuenta por resmas. Para cargar 5 cajas, ingresá 50 resmas. Un recuento corresponde al stock libre, sin las entregas ya reservadas.</p></div><div class="modal-actions"><button class="primary">Guardar movimiento</button></div></form></dialog>
  <dialog id="supplyReportDialog"><div class="modal-head"><h2>Informar los que retiran</h2><button type="button" class="icon-btn" data-close-supply="supplyReportDialog">×</button></div><div class="message-body"><p id="supplyReportContext" class="security-note"></p><textarea id="supplyReportMessage" rows="6" readonly></textarea></div><div class="modal-actions"><a class="primary" id="supplyWhatsapp" target="_blank" rel="noopener noreferrer">WhatsApp</a><button class="secondary" id="copySupplyReport">Copiar mensaje</button></div></dialog>`);
  document.querySelectorAll('[data-close-supply]').forEach(b=>b.onclick=()=>$('#'+b.dataset.closeSupply).close());
  $('#newSupplyProduct').onclick=()=>openSupplyProduct();
  $('#supplyCatalogSearch').oninput=e=>{supplySearch=e.target.value;renderSupplies()};
  $('#showArchivedSupplies').onchange=e=>{showArchivedSupplies=e.target.checked;renderSupplies()};
  $('#supplyForm [name=product]').onchange=updateSupplyHint;
  $('#supplyProductForm').onsubmit=e=>{e.preventDefault();supplyAction(()=>{const f=e.target;if(f.elements.id.value)editSupplyProduct(ensureSupplies(),f.elements.id.value,f.elements.name.value,f.elements.unit.value,f.elements.quantity.value);else addSupplyProduct(ensureSupplies(),f.elements.name.value,f.elements.unit.value,f.elements.quantity.value);$('#supplyProductDialog').close()})};
  $('#supplyForm').onsubmit=e=>{e.preventDefault();supplyAction(()=>{assignSupply(ensureSupplies(),Object.fromEntries(new FormData(e.target)));$('#supplyDialog').close()})};
  $('#supplyStockForm').onsubmit=e=>{e.preventDefault();supplyAction(()=>{const f=e.target,s=ensureSupplies(),building=f.elements.building.value,product=f.elements.product.value,quantity=Number(f.elements.quantity.value);if(!Number.isSafeInteger(quantity)||quantity<0)throw Error('Cantidad inválida.');const delta=f.elements.operation.value==='set'?quantity-supplyStock(s,building,product):supplyAmount(quantity);supplyMovement(s,building,product,delta,f.elements.reason.value.trim());$('#supplyStockDialog').close()})};
  $('#copySupplyReport').onclick=async()=>{try{await navigator.clipboard.writeText($('#supplyReportMessage').value);toast('Mensaje copiado')}catch{toast('No se pudo copiar. Seleccioná el texto y copialo manualmente.')}};
}
function supplyAction(action){try{if(savePending)throw Error('Hay un guardado en curso. Intentá nuevamente en unos segundos.');action();save()}catch(error){toast(error.message)}}
function renderSupplies(){
  if(!$('#supplyDepots'))return;const s=ensureSupplies(),today=supplyToday();
  const reportDates={};document.querySelectorAll('[data-supply-report-date]').forEach(el=>{reportDates[el.dataset.supplyReportDate]=el.value});
  const tabs=$('#supplyDepotTabs');if(tabs){tabs.innerHTML=['Diagonal','Callao','Montevideo'].map((name,i)=>`<button class="secondary ${i===selectedSupplyDepot?'active':''}" aria-pressed="${i===selectedSupplyDepot}" data-supply-tab="${i}">${name}</button>`).join('');document.querySelectorAll('[data-supply-tab]').forEach(b=>b.onclick=()=>{selectedSupplyDepot=Number(b.dataset.supplyTab);renderSupplies()})}
  const summary=$('#supplySummary'),active=s.products.filter(p=>!p.archived),current=s.depots[BUILDINGS[selectedSupplyDepot]];if(summary)summary.innerHTML=`<article><span>Insumos activos</span><strong>${active.length}</strong></article><article><span>Sin stock disponible</span><strong>${active.filter(p=>!current.stock[p.id]).length}</strong></article><article><span>Entregas pendientes</span><strong>${s.assignments.filter(a=>a.building===BUILDINGS[selectedSupplyDepot]&&a.status==='Pendiente').length}</strong></article>`;
  $('#supplyDepots').innerHTML=BUILDINGS.map((building,index)=>{
    const d=s.depots[building],label=['Diagonal','Callao','Montevideo'][index],peopleOptions='<option value="">Sin referente</option>'+state.people.map(p=>`<option value="${esc(p.id)}" ${d.referee===p.id?'selected':''}>${esc(p.name)}</option>`).join('');
    const assignments=s.assignments.filter(a=>a.building===building).slice().reverse();
    return `<section class="panel supply-depot-panel" ${index===selectedSupplyDepot?'':'hidden'}><h2>Depósito ${label}</h2><label>Empleado referente<select data-supply-ref="${index}">${peopleOptions}</select></label><h3>Stock disponible</h3><div class="table-wrap"><table class="supply-table"><thead><tr><th>Insumo</th><th>Cantidad</th><th></th></tr></thead><tbody>${visibleSupplyProducts(s).map(p=>`<tr><td>${esc(p.name)}${p.archived?'<small class="supply-inactive">Dado de baja</small>':''}${p.id==='a4'?'<small>10 resmas = 1 caja</small>':''}</td><td><strong>${esc(d.stock[p.id])}</strong><small>${esc(p.unit)}</small></td><td class="supply-product-actions"><button class="secondary" data-supply-edit="${esc(p.id)}">Editar</button>${p.archived?`<button class="secondary" data-supply-restore="${esc(p.id)}">Restaurar</button>`:`<button class="danger" data-supply-archive="${esc(p.id)}">Dar de baja</button>`}<button class="secondary" ${p.archived?'disabled':''} data-supply-stock="${index}" data-product="${esc(p.id)}">Stock</button></td></tr>`).join('')}</tbody></table></div><div class="supply-controls"><button class="primary" data-assign-supply="${index}">+ Asignar entrega</button><label>Miércoles a informar<input type="date" data-supply-report-date="${index}" value="${reportDates[index]||nextSupplyWednesday(new Date(today+'T10:00:00Z'))}"></label><button class="secondary" data-report-supply="${index}">Informar los que retiran</button></div><h3>Entregas / reservas</h3><div class="supply-assignment-list">${assignments.filter(a=>a.status==='Pendiente').map(a=>{const p=s.products.find(p=>p.id===a.product);return `<article class="supply-assignment"><strong>${esc(a.dependency)}</strong><p>${esc(a.quantity)} ${esc(p?.name||a.product)} · ${esc(fmt(a.pickupDate))}</p><span class="badge ${a.status==='Retirado'?'status-resuelto':a.status==='Cancelado'?'status-sin-asignar':'status-en-proceso'}">${esc(a.status)}</span>${a.status==='Pendiente'?`<div class="service-actions"><button class="secondary" data-supply-collected="${esc(a.id)}">Retirado</button><button class="danger" data-supply-cancel="${esc(a.id)}">Cancelar</button></div>`:''}</article>`}).join('')||'<p>No hay entregas asignadas.</p>'}</div><details><summary>Historial de entregas</summary>${assignments.filter(a=>a.status!=='Pendiente').map(a=>`<p>${esc(a.dependency)} · ${esc(a.quantity)} ${esc(s.products.find(p=>p.id===a.product)?.name||a.product)} · ${esc(a.status)} · ${esc(fmt(a.pickupDate))}</p>`).join('')||'<p>No hay entregas finalizadas.</p>'}</details><details><summary>Informes generados</summary>${s.reports.filter(r=>r.building===building).slice(-5).reverse().map(r=>`<p>${esc(fmt(r.pickupDate))} · ${esc(formatCreatedAt(r.createdAt))}</p><p class="note-text">${esc(r.text)}</p>`).join('')||'<p>No hay informes.</p>'}</details></section>`;
  }).join('');
  document.querySelectorAll('[data-supply-edit]').forEach(b=>b.onclick=()=>openSupplyProduct(b.dataset.supplyEdit));
  document.querySelectorAll('[data-supply-archive]').forEach(b=>b.onclick=()=>{if(confirm('Dar de baja este insumo en los tres depósitos? Se conservarán el stock y el historial; podrás restaurarlo.'))supplyAction(()=>archiveSupplyProduct(s,b.dataset.supplyArchive))});
  document.querySelectorAll('[data-supply-restore]').forEach(b=>b.onclick=()=>supplyAction(()=>restoreSupplyProduct(s,b.dataset.supplyRestore)));
  document.querySelectorAll('[data-supply-ref]').forEach(el=>el.onchange=()=>supplyAction(()=>{if(el.value&&!person(el.value))throw Error('Empleado no disponible.');s.depots[BUILDINGS[Number(el.dataset.supplyRef)]].referee=el.value}));
  document.querySelectorAll('[data-assign-supply]').forEach(b=>b.onclick=()=>openSupplyAssignment(Number(b.dataset.assignSupply)));
  document.querySelectorAll('[data-supply-stock]').forEach(b=>b.onclick=()=>{const f=$('#supplyStockForm');f.reset();f.elements.building.value=BUILDINGS[Number(b.dataset.supplyStock)];f.elements.product.value=b.dataset.product;$('#supplyStockTitle').textContent=s.products.find(p=>p.id===b.dataset.product)?.name||'';$('#supplyStockDialog').showModal()});
  document.querySelectorAll('[data-supply-collected]').forEach(b=>b.onclick=()=>supplyAction(()=>{changeSupplyStatus(s,b.dataset.supplyCollected,'Retirado')}));
  document.querySelectorAll('[data-supply-cancel]').forEach(b=>b.onclick=()=>{if(confirm('Cancelar la entrega y devolver la cantidad al stock?'))supplyAction(()=>{changeSupplyStatus(s,b.dataset.supplyCancel,'Cancelado')})});
  document.querySelectorAll('[data-report-supply]').forEach(b=>b.onclick=()=>openSupplyReport(Number(b.dataset.reportSupply)));
  $('#supplyMovements').innerHTML='<div class="table-wrap"><table><thead><tr><th>Fecha / hora</th><th>Depósito</th><th>Insumo</th><th>Movimiento</th><th>Saldo</th><th>Motivo</th></tr></thead><tbody>'+s.movements.filter(m=>m.building===BUILDINGS[selectedSupplyDepot]).slice(-100).reverse().map(m=>`<tr><td>${esc(formatCreatedAt(m.createdAt))}</td><td>${esc(m.building)}</td><td>${esc(s.products.find(p=>p.id===m.product)?.name||m.product)}</td><td>${m.delta>0?'+':''}${esc(m.delta)}</td><td>${esc(m.after)}</td><td>${esc(m.reason)}</td></tr>`).join('')+'</tbody></table></div>';
}
function openSupplyAssignment(index){const s=ensureSupplies(),f=$('#supplyForm');if(!s.products.some(p=>!p.archived)){toast('No hay insumos activos. Agregá o restaurá uno.');return}f.reset();f.elements.building.value=BUILDINGS[index];fillSelect(f.elements.dependency,dependenciesForBuilding(BUILDINGS[index]),'Seleccionar dependencia');f.elements.product.innerHTML=s.products.filter(p=>!p.archived).map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join('');f.elements.pickupDate.value=nextSupplyWednesday();updateSupplyHint();$('#supplyDialog').showModal()}
function updateSupplyHint(){const s=ensureSupplies(),f=$('#supplyForm'),p=s.products.find(p=>p.id===f.elements.product.value);if(!p)return;f.elements.quantity.value=p.defaultQuantity;$('#supplyStockHint').textContent=`Disponible: ${s.depots[f.elements.building.value].stock[p.id]} ${p.unit}.${p.id==='a4'?' Cantidad sugerida: 10 resmas (1 caja).':''}`}
function openSupplyReport(index){supplyAction(()=>{const s=ensureSupplies(),building=BUILDINGS[index],date=document.querySelector(`[data-supply-report-date="${index}"]`).value;if(!supplyWednesday(date))throw Error('Seleccioná un miércoles.');const assignments=pendingSupplyAssignments(s,building,date),text=supplyReportText(assignments),ref=person(s.depots[building].referee);s.reports.push({id:crypto.randomUUID(),building,pickupDate:date,createdAt:new Date().toISOString(),assignmentIds:assignments.map(a=>a.id),text,referee:ref?.id||''});$('#supplyReportMessage').value=text;$('#supplyReportContext').textContent=`Borrador para ${fmt(date)}. ${ref?'Referente: '+ref.name+'.':'No hay referente asignado.'} Incluye los pendientes hasta ese miércoles. Enviar ese día: el texto dice «hoy». No marca los retiros ni envía automáticamente.`;const raw=(ref?.phone||'').replace(/\D/g,''),phone=raw.length===10?'549'+raw:raw,link=$('#supplyWhatsapp');link.href=phone?`https://wa.me/${phone}?text=${encodeURIComponent(text)}`:'#';link.classList.toggle('disabled',!phone);link.setAttribute('aria-disabled',String(!phone));link.onclick=e=>{if(!phone){e.preventDefault();toast('Cargá el WhatsApp del referente o copiá el mensaje.')}};$('#supplyReportDialog').showModal()})}
