const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');
const ctx=vm.createContext({Date,Intl,structuredClone,console,crypto:require('node:crypto').webcrypto});
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/bootstrap\(\);\s*$/,''),ctx);
const buildings=vm.runInContext('BUILDINGS',ctx);
const workspace={services:[{id:'S-0001',building:buildings[0],serviceType:'LIMPIEZA',provider:'Empresa existente'}]};
assert.equal(ctx.ensureDefaultServices(workspace),true);
assert.equal(workspace.services.length,20);
assert.equal(new Set(workspace.services.map(s=>s.id)).size,20);
assert.equal(workspace.services[0].provider,'Empresa existente');
for(const [i,count] of [[0,7],[1,6],[2,7]])assert.equal(workspace.services.filter(s=>s.building===buildings[i]).length,count);
assert.ok(!workspace.services.some(s=>s.building===buildings[2]&&s.serviceType==='Caldera'));
assert.ok(!workspace.services.some(s=>s.building===buildings[1]&&s.serviceType==='Hidrantes'));
assert.deepEqual(Array.from(workspace.services.filter(s=>s.serviceType==='Detección de incendios').map(s=>s.building)),[buildings[2]]);
assert.equal(ctx.ensureDefaultServices(workspace),false);
workspace.services.pop();ctx.ensureDefaultServices(workspace);assert.equal(workspace.services.length,19);
vm.runInContext("state.people=[{id:'p1',name:'Nombre anterior',role:'Ayudante',building:BUILDINGS[0]}];state.orders=[{assignee:'p1'}];state.tools=[{holder:'p1'}]",ctx);
assert.equal(ctx.updatePerson({id:'p1',name:'Nombre nuevo',phone:'1155551234',role:'Electricidad',building:buildings[1]}),true);
assert.equal(vm.runInContext('state.people.length',ctx),1);
assert.equal(vm.runInContext('state.people[0].name',ctx),'Nombre nuevo');
assert.equal(vm.runInContext('state.orders[0].assignee',ctx),'p1');
assert.equal(vm.runInContext('state.tools[0].holder',ctx),'p1');
assert.equal(ctx.updatePerson({id:'no-existe',name:'Error'}),false);
ctx.updatePerson({name:'Otro empleado',role:'Ayudante',building:buildings[0]});
assert.equal(vm.runInContext('state.people.length',ctx),2);
const contacts=[21,12,1,31,11,13,10,2].map(n=>({name:`Juzgado Comercial N.º ${n}`}));
contacts.push({name:'Biblioteca',phone:'11111',building:'1211'});
const result=Array.from(ctx.searchContacts(contacts,'1').map(c=>ctx.courtNumber(c)));
assert.deepEqual(result,['1','10','11','12','13','21','31']);
assert.deepEqual(Array.from(ctx.searchContacts(contacts,'juzgado 1').map(c=>ctx.courtNumber(c))),result);
assert.equal(ctx.searchContacts([{name:'Secretaría General'},{name:'Biblioteca'}],'secr').length,1);
const timestamp='2026-09-17T15:30:45.000Z';
assert.match(ctx.formatCreatedAt(timestamp),/12:30:45/);
assert.match(ctx.formatCreatedAt('2026-09-17'),/hora no registrada/);
assert.equal(ctx.formatCreatedAt('mal valor'),'Creación no registrada');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.match(html,/id="personModalTitle"/);assert.match(html,/id="orderCreatedAt"/);
console.log('Pruebas v15: edición de personal, servicios, búsqueda numérica y fecha/hora: OK');
