const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=path.join(__dirname,'..');const c=vm.createContext({Date,Intl,structuredClone,console,crypto:require('node:crypto').webcrypto});
for(const file of ['contacts-data.js','supplies.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,file),'utf8').replace(/bootstrap\(\);\s*$/,''),c);
const buildings=vm.runInContext('BUILDINGS',c),workspace={},s=c.ensureSupplies(workspace);
assert.equal(s.products.length,6);assert.equal(Object.keys(s.depots).length,3);
c.ensureSupplies(workspace);assert.equal(s.products.length,6);
for(const b of buildings)assert.equal(s.depots[b].stock.a4,0);
c.supplyMovement(s,buildings[0],'a4',50,'Compra');
assert.equal(s.depots[buildings[0]].stock.a4,50);
assert.equal(s.depots[buildings[1]].stock.a4,0);
const request={building:buildings[0],dependency:'Juzgado N.º 1',product:'a4',quantity:10,pickupDate:'2026-09-23'};
const assignment=c.assignSupply(s,request);assert.equal(s.depots[buildings[0]].stock.a4,40);
c.changeSupplyStatus(s,assignment.id,'Retirado');assert.equal(s.depots[buildings[0]].stock.a4,40);
assert.throws(()=>c.changeSupplyStatus(s,assignment.id,'Retirado'));
const cancelled=c.assignSupply(s,request);assert.equal(s.depots[buildings[0]].stock.a4,30);
c.changeSupplyStatus(s,cancelled.id,'Cancelado');assert.equal(s.depots[buildings[0]].stock.a4,40);
assert.throws(()=>c.changeSupplyStatus(s,cancelled.id,'Cancelado'));
assert.throws(()=>c.assignSupply(s,{...request,quantity:41}));assert.equal(s.depots[buildings[0]].stock.a4,40);
assert.throws(()=>c.assignSupply(s,{...request,quantity:1.5}));
assert.throws(()=>c.assignSupply(s,{...request,pickupDate:'2026-09-24'}));
assert.throws(()=>c.assignSupply(s,{...request,building:buildings[1]}));
assert.throws(()=>c.assignSupply(s,{...request,quantity:-1}));
assert.throws(()=>c.supplyMovement(s,buildings[0],'a4',-41,'Error'));
const product=c.addSupplyProduct(s,'Cinta adhesiva','rollos',2);
for(const b of buildings)assert.equal(s.depots[b].stock[product.id],0);
assert.throws(()=>c.addSupplyProduct(s,'cinta ADHESIVA','rollos',1));
assert.throws(()=>c.addSupplyProduct(s,'','unidades',1));
assert.equal(c.nextSupplyWednesday(new Date('2026-09-18T12:00:00Z')),'2026-09-23');
assert.equal(c.nextSupplyWednesday(new Date('2026-09-23T10:59:59Z')),'2026-09-23');
assert.equal(c.nextSupplyWednesday(new Date('2026-09-23T11:00:00Z')),'2026-09-30');
assert.equal(c.nextSupplyWednesday(new Date('2026-12-31T12:00:00Z')),'2027-01-06');
assert.equal(c.supplyWednesday('2026-09-23'),true);assert.equal(c.supplyWednesday('2026-02-30'),false);
const first=c.assignSupply(s,request),later=c.assignSupply(s,{...request,pickupDate:'2026-09-30'});
assert.deepEqual(Array.from(c.pendingSupplyAssignments(s,buildings[0],'2026-09-23').map(a=>a.id)),[first.id]);
assert.equal(c.pendingSupplyAssignments(s,buildings[1],'2026-09-30').length,0);
assert.equal(c.pendingSupplyAssignments(s,buildings[0],'2026-09-30').length,2);
const text=c.supplyReportText([{dependency:'Juzgado N.º 1'},{dependency:'Juzgado N.º 1'},{dependency:'Juzgado N.º 4'},{dependency:'Sala B'}]);
assert.match(text,/1-4-B/);assert.match(text,/Avisame mañana los que retiraron/);
assert.doesNotMatch(text,/1211|Callao|Montevideo|¿|¡/);
assert.throws(()=>c.supplyReportText([]));
assert.match(c.supplyReportText([{dependency:'Juzgado N.º 1'}]),/los siguientes juzgados: 1/);
assert.doesNotMatch(c.supplyReportText([{dependency:'Mesa Receptora Montevideo'}]),/Montevideo/);
const roundTrip=c.ensureSupplies(JSON.parse(JSON.stringify(workspace)));
assert.equal(roundTrip.depots[buildings[0]].stock.a4,20);assert.equal(roundTrip.assignments.length,4);
assert.equal(s.movements[0].before,0);assert.equal(s.movements[0].after,50);
const nodes={'#supplyDepots':{},'#supplyMovements':{}};
c.document={querySelector:selector=>nodes[selector],querySelectorAll:()=>[]};
c.sampleSupplies=roundTrip;vm.runInContext('state.supplies=sampleSupplies',c);
c.renderSupplies();
for(const text of ['Depósito Diagonal','Depósito Callao','Depósito Montevideo','Informar los que retiran','Stock disponible'])assert.ok(nodes['#supplyDepots'].innerHTML.includes(text));
c.addSupplyProduct(roundTrip,'<img src=x onerror=alert(1)>','unidades',1);c.renderSupplies();
assert.ok(!nodes['#supplyDepots'].innerHTML.includes('<img src=x'));
assert.ok(nodes['#supplyDepots'].innerHTML.includes('&lt;img src=x'));
const originalStock=roundTrip.depots[buildings[0]].stock.a4;
c.editSupplyProduct(roundTrip,product.id,'Cinta de embalaje','rollos',3);
assert.equal(roundTrip.products.find(p=>p.id===product.id).defaultQuantity,3);
assert.throws(()=>c.editSupplyProduct(roundTrip,product.id,'Resmas de papel A4','rollos',3));
assert.throws(()=>c.editSupplyProduct(roundTrip,'a4','Papel A4','cajas',1));
assert.throws(()=>c.archiveSupplyProduct(roundTrip,'a4'),/pendientes/);
for(const a of roundTrip.assignments.filter(a=>a.status==='Pendiente'))c.changeSupplyStatus(roundTrip,a.id,'Retirado');
c.archiveSupplyProduct(roundTrip,'a4');
assert.equal(roundTrip.depots[buildings[0]].stock.a4,originalStock);
assert.throws(()=>c.assignSupply(roundTrip,request),/activo/);
assert.ok(!c.visibleSupplyProducts(roundTrip).some(p=>p.id==='a4'));
c.renderSupplies();assert.ok(!nodes['#supplyDepots'].innerHTML.includes('data-supply-edit="a4"'));
vm.runInContext('showArchivedSupplies=true',c);c.renderSupplies();
assert.ok(nodes['#supplyDepots'].innerHTML.includes('data-supply-edit="a4"'));
assert.ok(!nodes['#supplyDepots'].innerHTML.includes('data-supply-archive='));
const crossWorkspace={},cross=c.ensureSupplies(crossWorkspace);
c.supplyMovement(cross,buildings[1],'a4',10,'Compra');
c.assignSupply(cross,{...request,building:buildings[1]});
assert.equal(cross.depots[buildings[1]].stock.a4,0);
assert.equal(cross.depots[buildings[0]].stock.a4,0);
assert.throws(()=>c.assignSupply(cross,{...request,dependency:'No existe'}));
const persisted=c.ensureSupplies(JSON.parse(JSON.stringify({supplies:roundTrip})));
assert.equal(persisted.products.find(p=>p.id==='a4').archived,true);
c.restoreSupplyProduct(roundTrip,'a4');assert.equal(roundTrip.depots[buildings[0]].stock.a4,originalStock);
assert.equal(roundTrip.assignments.length,4);
vm.runInContext("supplySearch='embalaje';showArchivedSupplies=false",c);
assert.equal(c.visibleSupplyProducts(roundTrip).length,1);
console.log('Pruebas Insumos: stock, retiros, edición, baja, restauración, persistencia y búsqueda: OK');
