const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.join(__dirname,'..');
const context=vm.createContext({Date,Intl,structuredClone,console});
vm.runInContext(fs.readFileSync(path.join(root,'contacts-data.js'),'utf8'),context);
vm.runInContext(fs.readFileSync(path.join(root,'app.js'),'utf8').replace(/bootstrap\(\);\s*$/,''),context);
assert.ok(vm.runInContext('TEMPLATES.length>=30',context));
assert.ok(vm.runInContext("SPECIALTIES.includes('Administrativo')",context));
assert.equal(context.shortDependency('Juzgado Nacional de Primera Instancia en lo Comercial N.º 30'),'Juzgado N.º 30');
assert.equal(context.shortDependency('Juzgado 2'),'Juzgado N.º 2');
assert.equal(context.shortDependency('Sala F'),'Sala F');
vm.runInContext("state.people=[{id:'p1',name:'Carlos Benítez',role:'Administrativo'}]",context);
assert.equal(context.orderSpecialty({assignee:'p1',category:'Electricidad'}),'Electricidad');
assert.equal(context.orderSpecialty({assignee:'',category:'Sanitarios'}),'Plomería');
const message=context.assignmentText({id:'OT-1',assignee:'p1',title:'Cambio de tubo de luz',building:'Av. Callao 635',dependency:'Juzgado Nacional de Primera Instancia en lo Comercial N.º 10',location:'Puerta 8',description:'DESCRIPCION PRIVADA',priority:'Media',dueDate:''});
assert.match(message,/Hola Carlos/);assert.match(message,/Juzgado N.º 10/);
assert.doesNotMatch(message,/Benítez|DESCRIPCION|Especialidad|Te asignaron/);
assert.ok(message.length<230);
const tool={holder:'p1',assignedDate:'2026-09-10',toolStatus:'Entregada'};
assert.equal(context.registerToolReturn(tool,'2026-09-16T12:00:00Z'),true);
assert.equal(tool.holder,'');assert.equal(tool.toolStatus,'Disponible');
assert.equal(tool.returns[0].holderName,'Carlos Benítez');
assert.equal(tool.returns[0].assignedDate,'2026-09-10');
assert.equal(context.registerToolReturn(tool),false);assert.equal(tool.returns.length,1);
assert.ok(context.contactMatches({name:'Secretaría General',organization:'Cámara Comercial'},'camara secretaria'));
assert.ok(context.contactMatches({name:'Juzgado Comercial N.º 30'},'juzgado 30'));
const catalog=vm.runInContext('OFFICIAL_CONTACTS',context),contacts=[];
assert.ok(catalog.length>=32);
assert.equal(context.mergeOfficialContacts(contacts,catalog),catalog.length);
contacts[0].phone='Mi teléfono corregido';
assert.equal(context.mergeOfficialContacts(contacts,catalog),0);
assert.equal(contacts[0].phone,'Mi teléfono corregido');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert.doesNotMatch(html,/name="title"|name="specialty"/);
assert.equal((html.match(/id="newOrderBtn"/g)||[]).length,1);
assert.ok(html.indexOf('id="newOrderBtn"')>html.indexOf('id="ordersView"'));
// Regresión del formulario: ya no existen los controles title ni specialty.
const control=()=>({value:'',hidden:false,required:false,disabled:false,style:{},children:[],replaceChildren(){this.children=[]},append(option){this.children.push(option)}});
const form={elements:Object.fromEntries(['id','template','customTask','status','priority','assignee','category','description','building','dependency','location','dueDate'].map(key=>[key,control()])),reset(){Object.values(this.elements).forEach(c=>c.value='')}};
const nodes={'#orderForm':form,'#orderForm [name=assignee]':form.elements.assignee};
for(const name of ['customTaskLabel','orderModalTitle','deleteOrderBtn','finishOrderBtn','orderDialog'])nodes['#'+name]=control();
nodes['#orderDialog'].showModal=()=>{};
context.document={querySelector:selector=>nodes[selector],createElement:()=>control()};
context.openOrder();assert.equal(form.elements.customTask.disabled,true);
assert.equal(form.elements.template.disabled,true);
form.elements.category.value='Electricidad';context.refreshTaskOptions();
assert.equal(form.elements.template.disabled,false);
assert.match(form.elements.template.innerHTML,/Cambio de tubo de luz/);
assert.doesNotMatch(form.elements.template.innerHTML,/Pérdida en canilla/);
form.elements.template.value='Cambio de tubo de luz';
form.elements.category.value='Sanitarios';context.refreshTaskOptions();
assert.equal(form.elements.template.value,'');
assert.match(form.elements.template.innerHTML,/Pérdida en canilla/);
assert.doesNotMatch(form.elements.template.innerHTML,/Cambio de tubo de luz/);
assert.equal(context.orderSpecialty({assignee:'p1',category:'Sanitarios'}),'Plomería');
assert.ok(vm.runInContext("STATUSES.includes('Faltan insumos')",context));
for(const category of vm.runInContext('CATEGORIES',context)){
  const tasks=context.tasksForCategory(category);assert.ok(tasks.length>0);
  assert.ok(tasks.every(t=>t.category===category));
}
assert.ok(!context.tasksForCategory('Electricidad').some(t=>t.category==='Ascensores'));
assert.ok(!context.tasksForCategory('Mantenimiento general').some(t=>t.category==='Limpieza'));
form.elements.template.value='Otra tarea';context.toggleCustomTask();
assert.equal(form.elements.customTask.required,true);assert.equal(nodes['#customTaskLabel'].hidden,false);
form.elements.category.value='Administrativo';context.refreshTaskOptions();
form.elements.template.value='Control de inventario';context.applyTemplate({target:form.elements.template});
assert.equal(form.elements.category.value,'Administrativo');assert.equal(form.elements.customTask.disabled,true);
vm.runInContext("state.orders=[{id:'OT-ANTERIOR',title:'Trabajo anterior no catalogado',category:'Administrativo',status:'Faltan insumos',priority:'Media',assignee:'p1'}]",context);
context.openOrder('OT-ANTERIOR');assert.equal(form.elements.template.value,'Otra tarea');
assert.equal(form.elements.customTask.value,'Trabajo anterior no catalogado');
assert.equal(form.elements.category.value,'Administrativo');
assert.equal(form.elements.status.value,'Faltan insumos');
assert.doesNotMatch(html,/name="taskSpecialty"/);
assert.ok(html.indexOf('name="category"')<html.indexOf('name="template"'));
assert.equal((html.match(/name="category"/g)||[]).length,1);
context.FormData=class{constructor(target){return new Map(Object.entries(target))}};
let saved=0,lastToast='';context.save=()=>saved++;context.toast=message=>lastToast=message;
context.showAssignmentMessage=()=>{};nodes['#orderDialog'].close=()=>{};
vm.runInContext('state.orders=[]',context);
context.submitOrder({preventDefault(){},target:{category:'Electricidad',template:'Pérdida en canilla'}});
assert.equal(saved,0);assert.match(lastToast,/esa categoría/);
context.submitOrder({preventDefault(){},target:{category:'Sanitarios',template:'Pérdida en canilla',assignee:'p1',status:'Faltan insumos'}});
assert.equal(saved,1);
assert.equal(vm.runInContext('state.orders[0].specialty',context),'Plomería');
assert.equal(vm.runInContext('state.orders[0].status',context),'Faltan insumos');
console.log('Pruebas de tareas, WhatsApp, devolución, contactos y formulario: OK');
